### ISSUE TITLE
Underscores in schema property names produce strange titles

### ISSUE THREAD

**Issue by justparking** [museumsvictoria/nodel#118]
By example, the following nodel script:
```python
local_event_MyValue = LocalEvent({'schema': {'type': 'object', 'properties': {
        'first_born': {'type': 'string', 'order': 1},
        'second_born': {'type': 'string', 'order': 2}}}})
```

...produces this result:
![image](https://user-images.githubusercontent.com/5266533/33056143-f5c52558-ced7-11e7-8164-763960441348.png)

(notice the **first__95__born**, etc.)

**Comment by mcartmel** [comment]
Resolved

**Comment by justparking** [comment]
This is still an issue or recent changes have brought it back. Demonstrated here using latest build (r361):
![image](https://user-images.githubusercontent.com/5266533/42741951-fe6cdf8e-88f9-11e8-83d6-5f88fba52f72.png)

The code was:
```python
local_event_AddressBook = LocalEvent({'schema': {'type': 'array', 'items': {
        'type': 'object', 
        'properties': {
          'name': {'type': 'string'},
          'sys_label': {'type': 'string'},
          'type': {'type': 'string'}
    }}}})

def main():
  local_event_AddressBook.emit([{'name': 'XXXX', 'sys_label': 'YYYY', 'type': 'ZZZZ'}])
```

**Comment by mcartmel** [comment]
Fix was accidentally reverted. Fixed.
